### ISSUE TITLE
Pairing Zen30 with Homey 2023

### ISSUE THREAD

**Issue by LeeZeeMee** [koktail-nl/com.getzooz.issues#1]
**Describe the bug**
Zen30 will not pair with Homey 2023

**To Reproduce**

**Expected behavior**
Add my Zen30 z-wave switch to my Homey 2023

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Pixel fold]
 - OS: [android 14]
 - Browser [Google Chrome]
 - Version [??]

**Additional context**
Goes through the process of adding the device but fails at the end and says try again later.

**Comment by ghost** [comment]
Hi @LeeZeeMee. Thank you for your issue report. What ZWave frequency do you use on Homey? The device only supports: U.S./Canada/Mexico.

**Comment by LeeZeeMee** [comment]
I'm not really sure. I am in the US if that helps.

**Comment by koktaildotcom** [comment]
Are you pairing close to Homey? And did you try to factory reset your ZEN30? 

```
If your primary controller is missing or inoperable, you may need to reset
the device to factory settings. To complete the reset process manually,
press and hold the lower paddle on the dimmer for at least 15 seconds
until the LED indicators start ﬂashing, then release. Then immediately
press and hold the upper paddle on the dimmer for at least 15 seconds.
The LED indicators will ﬂash again to conﬁrm successful reset.
NOTE: All previously recorded activity and custom settings will be erased from the device’s memory.
```
