### ISSUE TITLE
Cannot add ZOOZ ZEN17 to Homey Pro 2019

### ISSUE THREAD

**Issue by bushtor** [koktail-nl/com.getzooz.issues#10]
**Describe the bug**
After having completed the two "button triple press" steps and entered the DSK ID, the process times out and displays "Something went wrong while communicating with the device".

**To Reproduce**
1. Click Add device in Homey
2. Select Zooz app
3. Select Universal Relay ZEN17
4. Click on Connect
5. Triple click the ZEN17's button two times
6. Enter the device's DSK ID (5 digits on label and same 5 digits are entered)
7. Process times out with "Something went wrong while communicating with the device"

**Expected behavior**
Process finished successfully....

**Screenshots**
![image](https://github.com/koktail-nl/com.getzooz.issues/assets/63792167/e76027e8-04f3-43c2-a65a-5b6c0799d75d)

**Desktop (please complete the following information):**
 - Win11Pro
 - Chrome multiple versions

**Smartphone (please complete the following information):**
 - Samsung Galaxy A52 5G
 - OS: One-UI 6.0
 Homey App ver 10.0.5

EDIT:  I now found that it partly works if I enter 00000 as DSK ID!  But then I have no encrypted connection and the ZEN17's two dry contact inputs are noe not present as Homey properties....

So still:  Anything you want me to try or test if you don't have the device available?

**Comment by koktaildotcom** [comment]
Before I dig into this issue. The device is only compatible with US Zwave (https://products.z-wavealliance.org/products/4132?selectedFrequencyId=-1), are you using this?

**Comment by bushtor** [comment]
Yes I have the US version.  Does it exist a European version too...?
Edit:  Maybe I'm wrong - as I don't have the device here with me so I can check.  I just knew that there was no EU approval sign on it, Only US approval....

**Comment by koktaildotcom** [comment]
And is your Homey also compatible with the US Zwave frequency?

**Comment by koktaildotcom** [comment]
> Yes I have the US version. Does it exist a European version too...?

No the ZEN17 is only working with the US Zwave frequency.

**Comment by bushtor** [comment]
Well I have a European Homey Pro 2019 and I could easily pair it with my two ZEN17 and their relay contacts work flawlessly now.  My only desire is if it is possible to get the two dry contact inputs available in Homey...

**Comment by koktaildotcom** [comment]
Dry contact issue is duplicate: https://github.com/koktail-nl/com.getzooz.issues/issues/2

**Comment by bushtor** [comment]
Yeah, I saw that.  Any chance that the dry inputs will be exposed later in the Homey ZOOZ app or is it not possible...

Anyhow FYI my ZEN17 relay outputs works nicely when I register it as 00000 with my European Homey Pro.

Thanks a lot for the app!!
