### ISSUE TITLE
Request for advanced controls

### ISSUE THREAD

**Issue by vlehmann1971** [koktail-nl/com.getzooz.issues#12]
Can you add advance controls (led color, a flow card if switch pressed twice, three etc.

**Comment by vlehmann1971** [comment]
dim ramp speed, led color, how led acts in different switch conditions, as well as a flow card like "with switch press up 2x then___ etc.

**Comment by koktaildotcom** [comment]
What device is missing these controls?

**Comment by vlehmann1971** [comment]
Zen 72 and zen77 dimmers, also nice for the zen71 and 76 switches

**Comment by koktaildotcom** [comment]
Only the ZEN30, ZEN32, ZEN34 are supporting the "switch pressed x times". Can you give a list of supported characteristics that you are missing per device?

**Comment by vlehmann1971** [comment]
In Homey pro app or desktop app no changes can be made to the switches at all.  My GE switches I can change LED characteristics.  I read the manual in some hubs you can change ramp speed, multi press options etc.  In Homey you cannot change anything.  I currently only have the ZEN 71 and 70 but would like to change my whole house to all ZOOZ if some more characteritcs can be added.

**Comment by kylescaletowin** [comment]
+1 to this - would be awesome to have these features in Homey. these are also available in HomeAssistant, Hubitat, etc.

**Comment by jayceegee87** [comment]
> +1 to this - would be awesome to have these features in Homey. these are also available in HomeAssistant, Hubitat, etc.

Even smartthings has this functionality, including for the Zen32.

**Comment by jayceegee87** [comment]
Is the multi-tap functionality on the roadmap for the zen37? It operates almost identically to the Zen32. 

I'm currently migrating my system from Smartthings to Homey Pro, and my current setup involves using the Zen32 and Zen37 multi-tap function to trigger different lighting scenes via a single button. It greatly enhances the usability of the Zooz scene controllers.

**Comment by HoneyBadger4000** [comment]
All zooz switches support these features and they are available on literally every other smart home platform. For me and a couple of my collegues this is the feature that is preventing us from adopting and recommending Homie. Multitap functionality is integrated into smart our homes with zooz paddle switchs in ways that would be disruptive to replace. I've been coming back to this thread several times over the past few months hoping there would be progress on it. I'll keep my hopes up.

**Comment by koktaildotcom** [comment]
A flow card if switch pressed 1, 2, 3, 4, 5 times or hold and release is implemented into: ZEN30, ZEN32, ZEN34, ZEN37. Changing the advanced settings is implemented only in to ZEN30 and ZEN32 for now.

**Comment by koktaildotcom** [comment]
Added advanced settings for ZEN72 (coming in next release)
