### ISSUE TITLE
Support for Zooz Zen37 + Zen54 

### ISSUE THREAD

**Issue by kylescaletowin** [koktail-nl/com.getzooz.issues#13]
Is it possible that either of these devices will be added to the app soon? 

I tried syncing the Zen37 manually via Z-wave and the device really does not perform as intended, and there doesn't seem to be clear ways to optimize the config of manually synced devices. 

I realize the Zen54 is probably a lower demand device, and as such, I can live without that for a while, but adding the Zen37 to the list of supported devices would be greatly appreciated. I would much prefer them to the Zen34. 

Thanks for all you do!

**Comment by jayceegee87** [comment]
I'd like to second the request for Zen37 compatibility. I have 3 in my current smarthome setup and it isn't yet compatible with Homey Pro. My understanding is that it is a very popular product because it is essentially a battery powered version of the Zen32 scene controller.

**Comment by KeesWes** [comment]
Can you indicate if ZEN37 will be added to Homey?

**Comment by jayceegee87** [comment]
Just saw that zen37 was added! Thank you!
