### ISSUE TITLE
Zen ZEN72 and ZEN77, ZEN30 not recognized as lights

### ISSUE THREAD

**Issue by vlehmann1971** [koktail-nl/com.getzooz.issues#18]
**Describe the bug**
When sorting by type of device the zen 72 and 77 are not listed as lights.  This makes the tags all lights off not work for these devices.

**To Reproduce**
1. Go to device list on I phone 
2. Click on '.lights'
4. See error zen 72 and 77 not listed

**Expected behavior**

> ### _`[](url)`_

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kylescaletowin** [comment]
2nd this! If there is a workaround here, please let us know.

**Comment by koktaildotcom** [comment]
Added ZEN30 too

**Comment by koktaildotcom** [comment]
Fixed in next release
