### ISSUE TITLE
Zooz App with Zooz Water Leak Sensor ZSE42

### ISSUE THREAD

**Issue by keithsimp99** [koktail-nl/com.getzooz.issues#20]
**Describe the bug**
The Zooz water leak sensor is not reporting the status of the Water alarm to Homey Pro. In fact the device is showing no status at all, there is just a dash (-) where the status should be.  The battery status is being reported to Homey Pro, which would indicate that the device is communicating with the Homey Pro hub. I also confirmed this with the Homey Developer Tool and in fact the device is reachable.
I have tried adding this device through both the Zooz App as well as adding it as a Z-wave device.  Both with the same results.

**To Reproduce**
When the Zooz ZSE42 comes in contact with water the led light, on the device starts blinking, indicating that water has been detected.
Status within the Homey App is not reported. Should be either "Yes" for Water alarm or "No" for no alarm.

**Expected behavior**
Should see "Yes" for Water Alarm  or "No" for no alarm

Zooz App version: 1.0.4
Homey Pro version: 10.3.2
![Screenshot_20240314_162734_Homey](https://github.com/koktail-nl/com.getzooz.issues/assets/163474041/782170fb-8d47-4eec-8938-be9bcfee84cd)
![Screenshot_20240314_162821_Homey](https://github.com/koktail-nl/com.getzooz.issues/assets/163474041/3c15d521-c45d-4acb-a4a2-00dd2f99e5fa)

If you need more information, please reach out to me.
Thanks for your effort in creating this app.

Keith S.

**Comment by koktaildotcom** [comment]
I have tested the behavior of the XSE42 v1.0 and the device works like intended. What device version do you have?

**Comment by koktaildotcom** [comment]
relates to: https://github.com/koktail-nl/com.getzooz.issues/issues/14

**Comment by keithsimp99** [comment]
Looks like version 2.0
Thanks

Keith S.
________________________________

**Comment by kamilio** [comment]
Same problem, doesn't report back
