### ISSUE TITLE
Incorrect device type in Homey

### ISSUE THREAD

**Issue by RoccoAncona** [koktail-nl/com.getzooz.issues#22]
**Describe the bug**

Devices such as LIGHT switches Zen72 and Zen77 do not register as “lights” in homey

**To Reproduce**

1. Add a LIGHT switch
2. See if it shows up as a LIGHT in the room
3. It doesn’t 

**Expected behavior**
Lights switches should either identify as such when they are added, or there should be an option to select their within their setting page.  in the absence of that, it causes two problems:

1) they cannot be controlled as lights in that group in a room as part of Homey

2) Alexa will not recognize them as it looks for things like plugs and lights.  Since this is neither, it will not import them

At the very minimum, the gear icon should allow this type to be configurable as for instance, GE does on there plug-in modules.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: All
 - Browser All

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RoccoAncona** [comment]
![IMG_1978](https://github.com/koktail-nl/com.getzooz.issues/assets/58271404/cad6e59d-7d16-4c0a-9983-c97391befb7b)

**Comment by CCalRissian** [comment]
This update would be great for all zooz light switches:  zen71, zen72, zen73, zen74, zen76, zen77. 

Dual switch with light and relay (selectable for fan option): zen30

scene controller:  zen32

Plugs with option for selecting light: zen04, zen05, zen14, zen15

Rgbw dimmer:  zen31

**Comment by RoccoAncona** [comment]
> This update would be great for all zooz light switches:  zen71, zen72, zen73, zen74, zen76, zen77. 
> 
> 
> 
> Dual switch with light and relay (selectable for fan option): zen30
> 
> 
> 
> scene controller:  zen32
> 
> 
> 
> Plugs with option for selecting light: zen04, zen05, zen14, zen15
> 
> 
> 
> Rgbw dimmer:  zen31

Agreed.

Without it, Homey functionality is impaired since it doesn't know the switch is actually a "light".

AND, from what I can see, it may prevent the Amazon Echo platform from importing and voice controlling them as they are not discovered as "light", they don't get discovered at all as a result.

I'm surprised it hadn't been reported earlier.

**Comment by kamilio** [comment]
I have the same issue on my end, it would be awesome to hear some update or ETA. 

If you would open source the lib, I could help.

**Comment by RoccoAncona** [comment]
> I have the same issue on my end, it would be awesome to hear some update or ETA. 
> 
> 
> 
> If you would open source the lib, I could help. 

Agreed, at first I thought it would have the open source code since it was on GitHub but I didn't see it posted.  Would be easier to maintain if it were.  I'm using the <group> homey app as a workaround to fix the bug but that's clunky and shouldn't be necessary.

**Comment by RoccoAncona** [comment]
Homey support confirmed it's a bug in this app, they can't address it themselves and this isn't open sourced.

What is the status of addressing this "official" app?![image](https://github.com/koktail-nl/com.getzooz.issues/assets/58271404/d548819e-a2a5-4c35-a8fd-7b8022400557)

**Comment by koktaildotcom** [comment]
The device classes for ZEN30, ZEN72 and ZEN77 have been changed to 'light' in v1.0.7. The ZEN71 and ZEN76 devices have been changed to v1.0.8 (currently under review). The remaining devices are placed under 'socket' because they are not specifically designed for lighting options.

**Comment by RoccoAncona** [comment]
Thanks for the 1.0.8 update, I can confirm that switches now correctly appear as "lights" in Homey.

As far as switches that were added under the prior version that have the incorrect "button" class, is there a way to refresh or repair their classification without having to remove them all and break their current automations?

**Comment by kamilio** [comment]
Refresh would be awesome, pairing them again would mean removing all wall plates to get the codes...

**Comment by kamilio** [comment]
We could try changing the type to "socket", it should add an option to select the type. Maybe it could work without removing them all? 


https://community.homey.app/t/set-device-as-light/107261/6?u=kamil_jopek

**Comment by RoccoAncona** [comment]
> We could try changing the type to "socket", it should add an option to select the type. Maybe it could work without removing them all? 
> 
> 
> 
> 
> 
> https://community.homey.app/t/set-device-as-light/107261/6?u=kamil_jopek
> 
> 
> 
> 

Other device drivers let you choose that class any time, like this GE device

![image](https://github.com/koktail-nl/com.getzooz.issues/assets/58271404/7c818429-322a-4a78-8109-a356ea22741d)

**Comment by koktaildotcom** [comment]
I cannot find anything in the Homey documentation about this feature. Do you know how this should be implemented?

**Comment by RoccoAncona** [comment]
> I cannot find anything in the Homey documentation about this feature. Do you know how this should be implemented?


It seems to be a common capability in plug in modules which are more easily moved about.  My TP-Link and GE modules have it using their bespoke drivers.  But the generic z-wave and zigbee drivers by Athom also have that capability.  Here is a screenshot from all four:

![image](https://github.com/koktail-nl/com.getzooz.issues/assets/58271404/9ceda887-7e81-4f9d-bc26-a46a62587bde)

**Comment by RoccoAncona** [comment]
> this

In the Athom z-wave docs, there is a reference to creating Multi Channel Nodes "In order to give devices the ability to implement a command class multiple times, Z-Wave has Multi Channel Nodes"

I believe Athom has this driver package available on GitHub

Doc: https://apps.developer.homey.app/wireless/z-wave

![image](https://github.com/koktail-nl/com.getzooz.issues/assets/58271404/4946d741-4096-4f81-829d-d926d0271aa5)

**Comment by koktaildotcom** [comment]
I will test by setting the class back to socket. The "Multi Channel Nodes" is a different functionality.

**Comment by RoccoAncona** [comment]
> functionality

It seems like for most switches, a "light" class would be appropriate and Alexa compatible.  The way the four other dimmer module examples implement it allows for a more flexible class selection after pairing and perhaps would prevent everyone from having to remove and re-pair all their devices?

**Comment by koktaildotcom** [comment]
The solution to change the device class was not the right one, the class should be plug and in the device settings you can select that you plugged in a light. I only do not know if that device is exposed in the API so that Alexa will know its a light?

**Comment by RoccoAncona** [comment]
> The solution to change the device class was not the right one, the class should be plug and in the device settings you can select that you plugged in a light. I only do not know if that device is exposed in the API so that Alexa will know its a light?


Alexa recognizes classes "light" and "plug".  From within the Alexa app, you can define that a "light" is attached to a "plug" as shown in this config screen for a generic zigbee dimmer "plug" module in the Alexa app:

![image](https://github.com/koktail-nl/com.getzooz.issues/assets/58271404/a15c6f6b-9fe1-4430-98ac-f12f410282fa)

**Comment by RoccoAncona** [comment]
... though the Alexa app does not seem to recognize class "socket", which is where we started as changing the class to something it recognizes was appropriate IMHO.

![image](https://github.com/koktail-nl/com.getzooz.issues/assets/58271404/5821dfa3-c8d3-4999-afe6-7daf09af5e01)

**Comment by RoccoAncona** [comment]
... Homey however does not immediately associate "plugs" as "lights" in the app, which is why "plug" modules have a configurable class to select that a "light" is plugged in.

![image](https://github.com/koktail-nl/com.getzooz.issues/assets/58271404/9473d046-36b9-4ec1-9cdf-5293880fced4)

![image](https://github.com/koktail-nl/com.getzooz.issues/assets/58271404/1eac996b-4e47-439d-8130-198e52b9bdb8)

**Comment by koktaildotcom** [comment]
So you are saying that we need to change the device classes back to "socket" and you have to select the type "light" yourself and Alexa is recognizing that?

**Comment by RoccoAncona** [comment]
Changing it to "light" fixed the original issue, Alexa sees the Zooz devices correctly now as "lights" which is generally what walls witches often connect to.  Previously it did not see them at all, so that's progress.

The dialog we were having after that is two-fold:

1) Changing that class to "light" has the unfortunate side-effect which I believe will require every user to remove every Zooz switch they have from the app, reset the switch, break its associated automations and have to basically start from scratch with each switch to get the Homey app and Alexa to recognize its new class.  I was suggesting that other device types had a user-selectable class drop-down option and was asking whether that provided a better migration path forward rather than reset every device.

2) Some users might connect a Zooz switch not to a light as they can also be wired to devices like fans.  Again, a user-selectable class drop-down option would be a more flexible solution.

I would NOT go back to "socket" or whatever it initially was as that breaks the Alexa discoverability.  I was just saying "lights" is better than where we started and offering some thoughts on how to make the migration and integration more robust with a user-selectable class option as other devices use.

I wasn't sure if you had open-sourced any of the driver, it might make some of this easier down the road?

**Comment by CCalRissian** [comment]
Please make the zen32 a light.

**Comment by koktaildotcom** [comment]
I corrected all devices with correct device types with v1.0.12. When the device type is a socket you have to select 'what's plugged in'.

**Comment by RoccoAncona** [comment]
v1.0.12 is not available in the Homey App Store.  Still says v1.0.10.

**Comment by kamilio** [comment]
Hey, I wrote a mini script to update the device type without unpairing/pairing

```js
(async () => {
    const searchname = "Upstairs Light";
    const devices = await Homey.devices.getDevices()
    const [device] = Object.values(devices).filter(device => device.name.toLowerCase().includes(searchname.toLowerCase()))
    
    if (!device) {
      throw new Error("No device found")
    }
    
    device.class = "light";
    await Homey.devices.updateDevice({ id: device.id, device });
})();
```

Run it in https://tools.developer.homey.app/tools/api-playground

**Comment by RoccoAncona** [comment]
I gave it a try, changed the target to a Kitchen Ceiling Zooz switch as I assume it targets a specific switch and not recursive.  Seems to be giving an error on the await line.  Did I implement your snippet incorrectly?

[cid:95b6278c-0cd4-4aab-aba2-4ca0393295c2]
________________________________

**Comment by RoccoAncona** [comment]
![image](https://github.com/user-attachments/assets/f61d8ee4-a227-42d3-a075-c9e34a86befd)

**Comment by kamilio** [comment]
Sorry, let me fix that, I was running it different environment

**Comment by RoccoAncona** [comment]
No worries.  I'm traveling and just had a Windows notebook with me.  Happy to try it again.

Correct to assume you want that first line to target a device by exact name?

**Comment by kamilio** [comment]
Hey @RoccoAncona, updated the script, try again! 

This updates them one by one, it's easier to understand this way.

**Comment by RoccoAncona** [comment]
Wow, awesome!  A simple edit in searchname to target a device, takes about 5 seconds to execute.  Here's a before/after of it updating the class of my kitchen ceiling switch correctly and it now appears as a "light".  Well done!  So much easier than having to reset, re-add and repair all the broken automations.  Thank you!  😊

**Comment by RoccoAncona** [comment]
![image](https://github.com/user-attachments/assets/8b2151bf-3376-4f24-a3a1-e199d45b2b70)

**Comment by kamilio** [comment]
Awesome, happy to help. Also, I changed some of them to class `socket`. Homey then offers the option in the UI to select device. Just change the light string to socket, that's it.

**Comment by RoccoAncona** [comment]
I just updated every light in the house while traveling away from home, this saves so much time!

**Comment by RoccoAncona** [comment]
![image](https://github.com/user-attachments/assets/b4df8382-3a5b-4de1-891f-e80d586b7f6d)

**Comment by RoccoAncona** [comment]
... and setting to class "socket" in the script brings up the user option to define what is connected.  This was exactly what I was hoping for.

![image](https://github.com/user-attachments/assets/68a15b79-94cd-4bdd-9664-3c78b8853424)

**Comment by RoccoAncona** [comment]
I did add a new switch today and it did not get recognized as a "light".  Running the script fixes that issue.

What default class will all devices be recognized as?  It seems like that should either be "socket" or "light"?

**Comment by dyshuk** [comment]
> Hey, I wrote a mini script to update the device type without unpairing/pairing
> 
> ```js
> (async () => {
>     const searchname = "Upstairs Light";
>     const devices = await Homey.devices.getDevices()
>     const [device] = Object.values(devices).filter(device => device.name.toLowerCase().includes(searchname.toLowerCase()))
>     
>     if (!device) {
>       throw new Error("No device found")
>     }
>     
>     device.class = "light";
>     await Homey.devices.updateDevice({ id: device.id, device });
> })();
> ```
> 
> Run it in https://tools.developer.homey.app/tools/api-playground

OMG THANK YOU SO MUCH!!!! this is a life saver; sure takes forever because i have over 50 zooz switches, but amazing work !!!

**Comment by thaserge** [comment]
Add pls for ZEN71

![Image](https://github.com/user-attachments/assets/1248374c-e6b0-4040-909f-90b3f48c8269)
