### ISSUE TITLE
New Zooz ZSE18 (800 series chip) has variable set to null and will not work

### ISSUE THREAD

**Issue by fisheromega** [koktail-nl/com.getzooz.issues#23]
Homey Pro 
Zooz ZSE18 -- New 800 Chip
Motion Activated variable set to null (not true or false)

I did setup the old ZSE18 - 500 Chip and it works okay.  So, I am guessing the issue(s) is because it is the newer model.

![Screenshot_20240411-165956](https://github.com/koktail-nl/com.getzooz.issues/assets/7327817/44706579-dd18-41c0-87e8-db846acaecc1)

<html>
<body>
<div class="MuiGrid-root MuiGrid-container MuiGrid-justify-content-xs-space-between" style="margin: 0px; padding: 0px; outline: none; box-sizing: border-box; width: 1493px; display: flex; flex-wrap: wrap; justify-content: space-between;"><div class="MuiGrid-root MuiGrid-item" style="margin: 0px; padding: 0px; outline: none; box-sizing: border-box;"><h5 class="MuiTypography-root MuiTypography-h5 MuiTypography-gutterBottom" style="margin: 0px 0px 0.35em; padding: 0px; outline: none; box-sizing: inherit; font-size: 1.5rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.334; letter-spacing: 0em;"><input type="text" class="DeviceName" value="Motion detection sensor (ZSE18)" style="margin: 0px; padding: 5px 0px; outline: none; box-sizing: inherit; border-width: 2px; border-style: none none solid; border-color: rgb(255, 255, 255); border-image: initial; font-size: inherit; font-weight: inherit; width: 30vw; background: transparent; color: rgb(255, 255, 255); overflow: hidden; white-space: nowrap; text-overflow: ellipsis; transition: all 0.2s ease 0s;"></h5></div><div class="MuiGrid-root MuiGrid-item" style="margin: 0px; padding: 0px; outline: none; box-sizing: border-box;"><div class="IconMask" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; mask-position: center center; mask-repeat: no-repeat; mask-size: contain; background: white; mask-image: url(&quot;https://192-168-15-103.homey.homeylocal.com/api/icon/fe60db79-9f50-403f-955b-6eabda32a2e4&quot;); width: 24px; height: 24px; display: inline-block; vertical-align: middle;"></div></div></div>
Property | Value
-- | --
ID | 5833401e-77a7-4cb4-a453-0687094d47da
Name | Motion detection sensor (ZSE18)
Class | sensor
Driver | homey:app:com.getzooz:ZSE18
Ready | Yes
Available | Yes
Warning | No
Custom icon | No

<br style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit;"><h6 class="MuiTypography-root MuiTypography-subtitle1" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; font-size: 1rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.75; letter-spacing: 0.00938em;">Capabilities</h6><table class="MuiTable-root CapabilityTable" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; width: 1493px; display: table; border-spacing: 0px; border-collapse: collapse;"><thead class="MuiTableHead-root" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-header-group;"><tr class="MuiTableRow-root MuiTableRow-head" style="margin: 0px; padding: 0px; outline: 0px; box-sizing: inherit; height: 48px; color: inherit; display: table-row; vertical-align: middle;"><th class="MuiTableCell-root MuiTableCell-head MuiTableCell-paddingNone" scope="col" width="10%" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.5rem; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);">ID</th><th class="MuiTableCell-root MuiTableCell-head MuiTableCell-paddingNone" scope="col" width="15%" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.5rem; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);">Title</th><th class="MuiTableCell-root MuiTableCell-head MuiTableCell-paddingNone" scope="col" width="5%" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.5rem; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);">Type</th><th class="MuiTableCell-root MuiTableCell-head MuiTableCell-paddingNone" scope="col" width="10%" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.5rem; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);">Value</th><th class="MuiTableCell-root MuiTableCell-head MuiTableCell-paddingNone" scope="col" width="20%" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.5rem; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);">Set Value</th><th class="MuiTableCell-root MuiTableCell-head MuiTableCell-paddingNone" scope="col" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.5rem; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);">Last Changed</th></tr></thead><tbody class="MuiTableBody-root" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-row-group;"><tr class="MuiTableRow-root" style="margin: 0px; padding: 0px; outline: 0px; box-sizing: inherit; height: 48px; color: inherit; display: table-row; vertical-align: middle;"><td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);">measure_battery</td><td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);">Battery</td><td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);">number</td><td class="MuiTableCell-root MuiTableCell-body CapabilityType CapabilityType-object MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 0.875rem; color: rgb(255, 255, 255); display: table-cell; text-align: left; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit;">null</td><td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);"></td><td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 0.875rem; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.01071em; vertical-align: inherit; color: rgb(255, 255, 255);"></td></tr><tr class="MuiTableRow-root" style="margin: 0px; padding: 0px; outline: 0px; box-sizing: inherit; height: 48px; color: inherit; display: table-row; vertical-align: middle;"><td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 14px; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.14994px; vertical-align: inherit; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 41); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">alarm_motion</td><td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 14px; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.14994px; vertical-align: inherit; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 41); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Motion alarm</td><td class="MuiTableCell-root MuiTableCell-body MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; display: table-cell; font-size: 14px; text-align: left; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.14994px; vertical-align: inherit; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 41); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">boolean</td><td class="MuiTableCell-root MuiTableCell-body CapabilityType CapabilityType-object MuiTableCell-paddingNone" style="margin: 0px; padding: 0px; outline: none; box-sizing: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 14px; color: rgb(255, 255, 255); display: table-cell; text-align: left; font-weight: 400; line-height: 1.43; border-bottom: 1px solid rgb(81, 81, 81); letter-spacing: 0.14994px; vertical-align: inherit; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 35, 41); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">null</td><br class="Apple-interchange-newline">
</body>
</html>

**Comment by fisheromega** [comment]
[New Text Document.txt](https://github.com/koktail-nl/com.getzooz.issues/files/14960196/New.Text.Document.txt)

Here is a log file.

**Comment by rexsmith317** [comment]
I have the same issue. Version with 800 chip includes fine but does not work.

**Comment by koktaildotcom** [comment]
We are currently waiting for a test device with the 800 chip to check this behavior.

**Comment by koktaildotcom** [comment]
Just added support for the ZSE18 800 series, will be in the next release
