### ISSUE TITLE
New Zooz ZSE18 (800 series chip) - Add more functionality

### ISSUE THREAD

**Issue by fisheromega** [koktail-nl/com.getzooz.issues#24]
The Zooz ZSE18 had more features that can be modified on other hubs (like Hubitat).  It would be nice to be able to control more of the functions of the sensor (and other Zooz products) without having to enter the Z-Wave Raw Configuration Parameters.

**Comment by koktaildotcom** [comment]
What features are you missing?

**Comment by fisheromega** [comment]
[image: image.png]
