### ISSUE TITLE
ZSE18 800LR Support

### ISSUE THREAD

**Issue by WiteRa88it** [koktail-nl/com.getzooz.issues#25]
**Is your feature request related to a problem? Please describe.**

Under the Zooz app within Homey it says the ZSE18 is a supported device, however this is very misleading because the new 800 series of the ZSE18 is not supported.

**Describe the solution you'd like**

I reached out to the Zooz team in February and they stated, "We have provided the samples to Homey; unfortunately, they have not provided us with an ETA for support. As we noted, this is out of our hands. We have provided the sample, and the integration is dependent on the Homey team."

When will support for the ZSE18 with the NEW 800 series Z-Wave chip be supported with Homey?

**Comment by koktaildotcom** [comment]
Thanks for your report, we didn't receive a ZSE18 800 series. I have received a lot of 700 series devices and therefor missing integrations with the 800 series. I have asked if they can send them so we can make an integration for the 800 series as well.

**Comment by WiteRa88it** [comment]
@koktaildotcom have you received any 800 series devices yet? If so, do you have an eta on when we can expect added support? Thanks!

**Comment by koktaildotcom** [comment]
Hi! Yes I received 800 serie devices. I will add these devices coming weeks.

Please be aware that it can take a while for it to be released in public.

**Comment by koktaildotcom** [comment]
Just added support for the ZSE18 800 serie, will be in the next release

**Comment by WiteRa88it** [comment]
@koktaildotcom I'd assume this would get closed when a new version of ZooZ App is released. I still see 1.0.8 in Homey. Why was this closed if a new version hasn't been released? Thanks.

**Comment by koktaildotcom** [comment]
There are some extra devices that are added in the test release and all this will be available in next release. We are just testing carefully.

**Comment by WiteRa88it** [comment]
@koktaildotcom I see. When do you anticipate the new version testing completing?

**Comment by koktaildotcom** [comment]
Its done when it is done

**Comment by WiteRa88it** [comment]
@koktaildotcom Just curious about an estimate. Estimates are standard in development and QA. Your response is pretty in your dutch language, an oetlul response. The community appreciates all your hard work either way.

**Comment by koktaildotcom** [comment]
I published v1.0.10: see https://homey.app/nl-nl/app/com.getzooz/Zooz

PS: I had already mentioned that it would be completed in the coming weeks, so it was not about estimates. "It's done when it's done" wasn't meant to be annoying. Its a clear messages that you have to wait until it is released. The project must go through a QA process over which I have no control.
