### ISSUE TITLE
ZSE41 Resets on Wake Up

### ISSUE THREAD

**Issue by brethomp** [koktail-nl/com.getzooz.issues#26]
**Describe the bug**
I have been working with Zooz Support on this and we can both verify that the issue is with the Homey App implementation of this device and not with the hardware its self. 

Simply, when this door/window sensor "wakes up" on its interval, which defaults to every 12 hours. If the sensor is in the open state (alarm), it resets to closed, even though the status of the door/window has not changed. This shows up in the Homey logs, but as Zooz turned off the alarm. The next time the door/window is closed that is skipped in the logs.  

This makes it difficult to have flows that change when these doors or windows are open for long periods of time, as eventually Homey falsely reports them as closed. Please fix.

**To Reproduce**
1. Determine when the wake up time is, usually every 12 hours staring at the time that the device first received battery power. 
2. Separate the device and magnet, and leave them separated.
3. Wait for the wake up to happen and the device will be reported as closed in Homey.

**Expected behavior**
The open/closed state of the device should remain unchanged when the device wakes up and reports in.

**Comment by koktaildotcom** [comment]
I have removed the update on wake up, can you please test this behavior with the coming release?
