### ISSUE TITLE
Q Sensor ZSE11 does not receive Motion alarm

### ISSUE THREAD

**Issue by Benaiah-Son-of-Jehoiada** [koktail-nl/com.getzooz.issues#28]
**Describe the bug**
Q Sensor ZSE11 does not receive Motion alarm.  All other sensor inputs are received, but the motion alarm has never received data

**To Reproduce**
1. Pair Q Sensor ZSE11
2. Trigger motion as evidenced by blue LED flash
3. Observe that Homey Pro never receives the motion alarm status

**Expected behavior**
The Motion Alarm status should be received.

**Screenshots**
![image](https://github.com/koktail-nl/com.getzooz.issues/assets/170253381/81d69248-c2a2-4731-9973-f13b693c1763)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Version 125.0.6422.60 (Official Build) (64-bit)

**Additional context**
Change of location does not change the outcome.

**Comment by Benaiah-Son-of-Jehoiada** [comment]
I talked to the Zooz tech at SmartestHouse.com and the tech reported that the Homey Pro Zooz app does not support the 800 version of the Qsense and that they recently sent this device to Homey for the app to be updated. The question is should I just return the product or will the Homey app be updated soon?

**Comment by koktaildotcom** [comment]
We are trying to add these asap.

**Comment by Benaiah-Son-of-Jehoiada** [comment]
Thanks for the quick reply!  I'll hold on to it then.

**Comment by koktaildotcom** [comment]
Just added support for the ZSE11, will be in the next release
