### ISSUE TITLE
Dimmer implementation

### ISSUE THREAD

**Issue by realjvernon** [koktail-nl/com.getzooz.issues#3]
**Describe the bug**
Dimmer does not offer an on or off option therefore it isn't able to be used in the app and doesn't even show up for other systems like Google Home. 

**To Reproduce**
1. Add dimmer
2. Click dimmer tile and observe that nothing happens
3. Long press to open and you can only dim
4. Add homey to Google Home and observe that dimmers will not sync

**Expected behavior**
I expect that this is implemented as an on/off switch with dimmer capabilities. 

**Desktop (please complete the following information):**
Not desktop specific

**Smartphone (please complete the following information):**
 Not device specific

**Additional context**
Tested other dimmer brands and their implemention is correct. It shows up and is usable as an on/off switch and can be dimmed. It also syncs to Google home successfully. Tested also with virtual switch app by setting it up as an on/off switch with dimmer capabilities. This also functions as expected and also syncs to Google home.

**Comment by koktaildotcom** [comment]
What device are you referring to (ZEN72?) and did the device work in Homey as expected?

**Comment by koktaildotcom** [comment]
I added the missing on/off capability to ZEN72 and ZEN77 and will be available on the coming release

**Comment by realjvernon** [comment]
Perfect, thanks. Looking forward to this update.
