### ISSUE TITLE
Zooz Dimmer Switch Additional Functionality

### ISSUE THREAD

**Issue by WiteRa88it** [koktail-nl/com.getzooz.issues#30]
In the advanced settings support document on Zooz it specifies being able to pass certain values to parameters based on single and double taps of the paddle.

What I would like to be able to do in Homey is say, at night when I single tap the paddle to turn on my lights in a room, turn them on to custom brightness level 25%.

Unless I am mistaken, I cannot currently do that in Homey.

**Double Tap and Single Tap Behavior**

Parameter 12: Choose what you'd like the dimmer to do when you double-tap the upper paddle.

Values: 0 – the light will turn on to full brightness (default); 1 – the light will turn on to the custom brightness level set in parameter 18; 2 – the light will turn on to the maximum brightness level set in Parameter 11; 3 – double tap disabled. 

Size: 1 byte dec

**Parameter 25: Choose what you'd like the dimmer to do when you tap the upper paddle once.**

Values:  0 – the light will turn on to the last brightness level (default); 1 – the light will turn on to the custom brightness level set in parameter 18; 2 – the light will turn on to the maximum brightness level set in Parameter 11; 3 – the light will turn on to full brightness. 

Size: 1 byte dec

**Comment by koktaildotcom** [comment]
Added advanced settings for ZEN72 (coming in next release)
