### ISSUE TITLE
Access to sesitivity setting ZSE18 motion sensor

### ISSUE THREAD

**Issue by HoneyBadger4000** [koktail-nl/com.getzooz.issues#31]
**Is your feature request related to a problem? Please describe.**
Cannot change the motion sensitivity setting on zooz motion sensor. It is available on other platforms. 

**Describe the solution you'd like**
Access to that setting.

**Describe alternatives you've considered**
There are none.

**Comment by koktaildotcom** [comment]
I implemented the advanced settings in 1.0.13 (https://homey.app/a/com.getzooz/test)
