### ISSUE TITLE
Zooz ZSE42 Water Leak Sensor not reporting Water Leak Status properly in Homey Pro

### ISSUE THREAD

**Issue by mbcurler** [koktail-nl/com.getzooz.issues#32]
When the ZSE42 detects water, the blue LED indicator flashes on the ZSE42 itself, however the status is not updated in Homey Pro. I have seen a couple of closed issues here in github reporting essentially the same behavior.
I am not terribly technical so bare with me. For my devices I see both hardware and firmware versions are reported as 2 in the app.
When I place the sensor in a shallow plate of water, the LED blinks on the ZSE42, however in the Homey Pro app the status is simply a dash and the "water alarm" is never triggered in the Homey Pro app.

I have been reading up to see if it is a known issue, and besides the couple of closed issues within github, there is a very possible indicator of the root cause of the issue in the Home Pro Community forum:

> [Russell_Ebbing](https://community.homey.app/u/Russell_Ebbing)
> [25d](https://community.homey.app/t/water-alert-flow-not-working/103718/8)
> I suspect the problem with the zooz leak sensors is in zooz app.
> 
> I have two zooz (zse42) sensors, both had been problematic to pair but once paired they only report battery but not leak. Honey pro shows a status of “-“ with last update 54 years.
> 
> As a developer this is suspect to having a null variable in the zooz app code. Honey displays “-“ for null Boolean, and 54 years because this is the start of time for Homey. (Microsoft starts in 1975).
> 
> For me the Developer tool site shows the z-wave connected. However a clue to why water sensor does not work comes from the devices area of the developer tools site.
> 
> Find the device, at the bottom in the capabilities section. Under the ID are two capabilities. “Measure_battery” which has a value of 100% for me. The second is “alarm_water” as a Boolean with a null value. Null is not a valid Boolean value. This is means a variable in code is not set.
> 
> This is easy to do with JavaScript programming. If zooz fixes a publishes the fix this will fix the broken water leak sensors.
> 
> If this is the problem zooz needs to do better testing before releasing code.

I went into the Developer Tool Site on Homey Pro and noted the same in my particular instance. That is the boolean for the alarm_water is set to "null". Therefore I think Russell Ebbing's explanation is most likely the cause of the issue.

![image](https://github.com/koktail-nl/com.getzooz.issues/assets/173616374/4862edb5-6453-4b78-8612-dc5be3503a43)

**Comment by koktaildotcom** [comment]
I added support for the 800 series (the 700 series works different). The 'update 54 years ago' is a bug in the Homey app, on the web app there is: 'No last known value'.

It will be available in the next release.
