### ISSUE TITLE
ZEN52 Double Relay

### ISSUE THREAD

**Issue by HoneyBadger4000** [koktail-nl/com.getzooz.issues#33]
**Describe the bug**
ZEN 52 Double Relay Listed as supported but appears as random z wave device with basically no functionality.

**Comment by koktaildotcom** [comment]
Can you check with the latest release?

**Comment by HoneyBadger4000** [comment]
Latest release was already out when I checked last. According to the
website it hasn't changed in 3 weeks. At that time no flow cards had been
assigned to it either. Unless the website is out of date.

**Comment by koktaildotcom** [comment]
Works like intended, my testing device is a ZEN52 700 Series Double Relay. Whats yours?
