### ISSUE TITLE
V1.0.12 missing?

### ISSUE THREAD

**Issue by RoccoAncona** [koktail-nl/com.getzooz.issues#36]
Changelog shows latest is v1.0.12.  

What's new shows v1.0.10

Downloading app installs 1.0.10

Is there a v1.0.12 with the latest "lights" class fix?![image](https://github.com/user-attachments/assets/0a87ad84-095b-4343-9c84-2246eeaa43b7)

![image](https://github.com/user-attachments/assets/aa186ffb-55e1-47bb-892d-a9b4ca833b46)

![image](https://github.com/user-attachments/assets/51720438-492a-404b-b752-ac44c47f3c66)

**Comment by koktaildotcom** [comment]
Released that version to production
