### ISSUE TITLE
Add support for zen20-800 power strip

### ISSUE THREAD

**Issue by eegzapp** [koktail-nl/com.getzooz.issues#37]
Please add support for the 5 port zen20-800 power strip.

It can currently be added as a generic z-wave device, but all ports are controlled as one.

Zooz links:

*Product page*
https://www.getzooz.com/zooz-zen20-power-strip/

*Manual*
https://www.getzooz.com/downloads/zooz-power-strip-zen20-ver3-manual.pdf

**Comment by koktaildotcom** [comment]
When added as generic z-wave device you don't get all capabilities of the device. What version of the app are you using?

**Comment by eegzapp** [comment]
Hi @koktaildotcom,

My info:
  Homey Pro: v12.0.2
  App version: 8.4.0.1538
  Node JS: v18.20.4
  Zooz app: v1.0.12

**Comment by koktaildotcom** [comment]
I fixed a bug for this in 1.0.13 (https://homey.app/a/com.getzooz/test)

**Comment by eegzapp** [comment]
I see the zen20 option now and it gets to the point where after I type in the code and hit enter, it makes the power strip "click", but then I get a dialog saying "Unable to Connect" "Something went wrong when communicating with the device".
(The zen20 is in the same room as the Homey, about 5 feet away)

Tried 3 times, but no luck so far.  Will keep at it.

Is there a way I can provide better diagnostic info?

**Comment by eegzapp** [comment]
Ah!  Got it to work by using all zeros for the pin.

Don't really need security for this, so works great for me.

Thanks for picking this up and fixing it so fast @koktaildotcom !
