### ISSUE TITLE
ZEN30 RELAY SWITCH Missing Capability Listener: onoff

### ISSUE THREAD

**Issue by g1zm0e** [koktail-nl/com.getzooz.issues#38]
**Describe the bug**
ZooZ zen30 relay (secondary) switch  appears to not trigger actions, when triggered from Homey Pro UI the following message appears 'Missing Capability Listener: onoff'

**To Reproduce**
1. Install ZooZ app
2. Install ZooZ ZEN30 in Dimmer Light configuration
3. Adopt ZooZ ZEN30
4. Adoption generates 2 tiles; DIMMER (WORKS) and SWITCH (GIVES ERROR)
5. Create a flow when ZOOZ SWITCH ZEN30 is turned on (or off) create a timeline event for 'hello world'
6. Go to Switch and click Relay, no timeline event will be generated
7. Go to app and select ZOOZ SWITCH ZEN30
8. Click on/off button and get error 'Missing Capability Listener: onoff'

**Expected behavior**
Triggering the secondary button on or off updates state in homey and triggers flow. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS, MACOS
 - Browser Chrome, Safari, Firefox
 - Version MULTIPLE

**Smartphone (please complete the following information):**
 - Device: iphone 15 pro
 - OS: 17.6.1
 - Browser Default app, safari, chrome
 - Version multiple

**Additional context**
I tried to set raw commands to no avail, this appears to just be missing the appropriate attribute.

**Comment by g1zm0e** [comment]
Following up, it looks like homey classifies the lower button as a socket vs a onoff

**Comment by kamilio** [comment]
Hey, try updating the Zooz app, check whether it's the latest version https://github.com/koktail-nl/com.getzooz.issues/issues/17

Unfortunately, you have to unpair and pair the device again if you want to get it fixed.

**Comment by koktaildotcom** [comment]
I have tested this behavior but could not reproduce your issue
