### ISSUE TITLE
ZSE43 shows wrong open/closed state

### ISSUE THREAD

**Issue by malekim** [koktail-nl/com.getzooz.issues#39]
**Describe the bug**
The sensor shows an open state when it is vertical, not horizontal.

**To Reproduce**
1. Just pair the device

**Expected behavior**
The sensor should show an open state when it's in horizontal position.

**Smartphone (please complete the following information):**
- Homey Pro 2023

**Comment by koktaildotcom** [comment]
Thanks for reporting this issue. It will be fixed in coming release.
