### ISSUE TITLE
Plugged in Dropdown

### ISSUE THREAD

**Issue by chaosrain** [koktail-nl/com.getzooz.issues#40]
**Is your feature request related to a problem? Please describe.**
When adding Z-Wave switches from other manufacturers, Homey allows me to identify what's connected to that switch. That way, Homey accurately identifies it as a light, fan, etc. and the zone's buttons work properly.

**Describe the solution you'd like**
Would like a Plugged In dropdown to tell Homey what's connected to the switch: 
![image](https://github.com/user-attachments/assets/31339ff1-bc4b-4506-9526-399827dd92e0)

**Describe alternatives you've considered**
Another manufacturer's hardware.

**Additional context**

**Comment by kamilio** [comment]
Hey, I wrote a solution in other thread
https://github.com/koktail-nl/com.getzooz.issues/issues/22#issuecomment-2395588057

Change the class to "socket" and the menu will appear

However, don't close this issue. As if the device class is incorrectly assigned, it should be fixed.

**Comment by koktaildotcom** [comment]
This is already implemented
