### ISSUE TITLE
ZEN16 Auto Turn-Off Timer Not Working As Expected

### ISSUE THREAD

**Issue by dyshuk** [koktail-nl/com.getzooz.issues#42]
As I want to use this ZEN16 to control a garage door, I need any one of the relays to toggle on / off in quick succession. I assume I can do this by setting the the "Auto Turn-Off Timer" to 1 second in the advanced settings (see attached). It seems that the setting saves (verified by the developer tools; picture also attached), but it simply doesn't work as expected; the relay simply stays on.

![relay 1 advanced setting](https://github.com/user-attachments/assets/9871ac4f-dae1-4443-994b-fbbd62a13ef1)
![developer screen shot](https://github.com/user-attachments/assets/4b1f9f28-da24-43a8-bc8c-d7ec87d9b64e)

**Comment by dyshuk** [comment]
I reached out to Zooz directly and they directed me to change Parameters 2, 3, and 4 set to value 3.  This changes the ZEN16 to mode to "garage door momentary mode" and now works as expected.

**Comment by koktaildotcom** [comment]
Great to hear your issue is resolved
