### ISSUE TITLE
ZSE70 Will Not Connect

### ISSUE THREAD

**Issue by brethomp** [koktail-nl/com.getzooz.issues#44]
**Describe the bug**
I purchased 2 new ZSE70 outdoor motion sensors and both of them will not join into Homey. 

**To Reproduce**
They go through all the normal steps. Pressing the button 3x, twice, then asks for the security code. I know the security code is correct since it does not error immediately.  Then sits at a loading screen for several seconds, and eventually produces an error message stating that Homey could not communicate with the device.

Attempted from both the Web and Phone App interfaces, same result.

Log of one attempt attached.
[ZSE70Log.txt](https://github.com/user-attachments/files/17784595/ZSE70Log.txt)

I do note from the developer tools that the device does seem to join the Z-Wave network, it is just Homey that is not recognizing the success.  Evidenced by the logs showing events from this device that look normal to me, so it appears to be on the network.

**Expected behavior**
Complete the Join network process.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Edge
 - Version current

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 15
 - Browser Homey App
 - Version current

**Comment by dyshuk** [comment]
it's possible this is a similar issue as the ZEN16 and ZEN17.  Try entering 0000 for the security code; doing so (if this works) will add it a an unsecure device, but i wouldn't be all too concerned about that.

**Comment by brethomp** [comment]
Thank you, that did work. This would still be a bug, but at least I can use these sensors for now.

**Comment by brethomp** [comment]
If this is completed, does that mean that I could re-add these motion sensors securely now? Which version of the Zooz App do I need to have for the fix to apply?

**Comment by dyshuk** [comment]
> If this is completed, does that mean that I could re-add these motion sensors securely now? Which version of the Zooz App do I need to have for the fix to apply?

I think @koktaildotcom marked it as complete because it seems this is a Homey issue and not a zooz app issue.
