### ISSUE TITLE
ZEN77 Dimmer not listed as a "Light" in Homey

### ISSUE THREAD

**Issue by brethomp** [koktail-nl/com.getzooz.issues#45]
**Describe the bug**
It appears that the ZEN77 800LR in wall dimmer is not categorized in Homey as a "Light", or it does not have the what's "Plugged In" feature to tell Homey that it is a light, like the generic Z-Wave driver does. This causes many issues with the Homey interface:
- These switches will not respond to the built-in flow cards for lights, like the Zone cards for "Turn **All Light** Off"
- In the Phone App, on the Devices tab, there is a Lights button/filter at the top, these switches are not listed there.
- Dashboard Widgets for Lights don't have access to these dimmers.

**To Reproduce**
Add a ZEN77 to the hub.
Check the 3 items listed above.

**Expected behavior**
These in wall dimmers should be recognized as a "Light" by default. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version Current

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: [e.g. Android 15
 - Browser Stock
 - Version current

**Additional context**
Please reply if there is a work-around for this issue.

**Comment by koktaildotcom** [comment]
Class 'button' needs to be 'light' indeed. Fixed in v1.0.15 (on test right now)
