### ISSUE TITLE
Switches not being enrolled consistantly 

### ISSUE THREAD

**Issue by andrewmbenson** [koktail-nl/com.getzooz.issues#51]
**Describe the bug**
Identical Zooz ZEN77 and ZEN76 switches are being enrolled differently through the Homey application.  Even though they are enrolled in exactly the same manner, sometime the switch has a status indicator of "Not Configurable" and other times it shows as "None".  When it shows as none, there is no indicator, when it is "Not Configurable" it shows in the Homey app with a circular light indicator.  This would not be a huge deal, except for the fact that when the indicator is "None" the device will not show up in Alexa, and thus cannot be voice controlled.  Switches with the indicator work fine with the Alexa Skill enabled.

**To Reproduce**
I am unable to reproduce in any reliable manner

**Expected behavior**
Switches should enroll constantly

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
iPhone 16 Pro - 18.1.1

**Additional context**
I have tried many other things to resolve the Alexa problem.  Unlinking and relinking Alexa and Homey.  I even set up a new Alexa account and had the same problem.  The only difference I can see between the switches that work in Alexa and those that don't is that indicator.  I have also tried removing the switches from Homey and re-enrolling them many times without success.  The switches are all new, are the same version, and are on the same firmware version.

**Comment by dyshuk** [comment]
https://github.com/koktail-nl/com.getzooz.issues/issues/22#issuecomment-2395588057

**Comment by koktaildotcom** [comment]
The ZEN71, ZEN73, ZEN76 had a 'switch' class so you have to determine what is 'plugged in'. Because that behavior is not clear to everyone and the devices are used 99% for lightning I converted the devices back to 'light'.

The devices should be re-paired to Homey or you have to run this script:

```
(async () => {
    const searchname = "Upstairs Light";
    const devices = await Homey.devices.getDevices()
    const [device] = Object.values(devices).filter(device => device.name.toLowerCase().includes(searchname.toLowerCase()))
    
    if (!device) {
      throw new Error("No device found")
    }
    
    device.class = "light";
    await Homey.devices.updateDevice({ id: device.id, device });
})();
```

**Comment by andrewmbenson** [comment]
Thank you for the reply and the prompt response.  Just a couple of questions:

1. Is this a permanent fix, so that any new devices will enroll with light indicator and should populate to Alexa?

2. Do I copy and paste this script into HomeyScript and run it?  I assume I need to change the “Upstairs Light” to the name of the switch that I am correcting.

Thank you,

Andrew Benson


On Dec 13, 2024, at 2:36 AM, Leendert de Kok | koktail.nl ***@***.***> wrote:



The ZEN71, ZEN73, ZEN76 had a 'switch' class so you have to determine what is 'plugged in'. Because that behavior is not clear to everyone and the devices are used 99% for lightning I converted the devices back to 'light'.

The devices should be re-paired to Homey or you have to run this script:

(async () => {
    const searchname = "Upstairs Light";
    const devices = await Homey.devices.getDevices()
    const [device] = Object.values(devices).filter(device => device.name.toLowerCase().includes(searchname.toLowerCase()))

    if (!device) {
      throw new Error("No device found")
    }

    device.class = "light";
    await Homey.devices.updateDevice({ id: device.id, device });
})();
