### ISSUE TITLE
ZEN52 issue

### ISSUE THREAD

**Issue by ghost** [koktail-nl/com.getzooz.issues#7]
Does not recognize the ZEN52 DOUBLE RELAY. So the device gets added as regular Z-wave device. Unable to see the options for multiple switches and more under regular Z-wave device.

**Comment by ghost** [comment]
Relates to: https://github.com/koktail-nl/com.getzooz.issues/issues/5

**Comment by koktaildotcom** [comment]
Cannot reproduce
