### ISSUE TITLE
ZEN77 on/off functionality not working on Mobile or Web

### ISSUE THREAD

**Issue by emart1988** [koktail-nl/com.getzooz.issues#8]
**Describe the bug**
I added my first ZEN77 dimmer to Homey Pro (2023). The one thing I am missing is that using the tile on the devices page I cannot simply turn on/off the switch. I have to do a long press to go in the switch and use the dimmer function. Am I missing something here? Any help will be greatly appreciated.

**To Reproduce**
Just add ZEN77 Dimmer to Homey Pro and try to use the tile to turn on/off the light attached.

**Expected behavior**
Expecting to have the attached lights turn on/off

**Screenshots**
![thumbnail_Screenshot 2023-12-20 at 11 13 37 AM](https://github.com/koktail-nl/com.getzooz.issues/assets/66457083/48a3c075-0934-4898-906e-a57db071c5c5)

**Smartphone (please complete the following information):**
 - Device: iphone 15
 - OS: ios 17.2

**Comment by koktaildotcom** [comment]
Thank you for reporting this issue. It will be solved in the coming release.

**Comment by emart1988** [comment]
Thank you! looking forward to using the device once the update is released.
